name: Release Check

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  dependencyReview:
    uses: ./.github/workflows/dependencyReview.yaml
